#!/usr/bin/env python3

import os, sys

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'releasetools'))
from releasetools import blockimgdiff, sparse_img

def main(INPUT_IMAGE, OUT_DIR, VERSION):
    __version__ = '2.0'
    print('img2sdat binary - version: %s' % __version__)

    if not os.path.isdir(OUT_DIR):
        os.makedirs(OUT_DIR)

    OUT_FILE = os.path.join(OUT_DIR, os.path.splitext(os.path.basename(INPUT_IMAGE))[0])

    blockimgdiff.common.OPTIONS.cache_size = 4 * 4096

    # Construct image
    INPUT_IMAGE = sparse_img.SparseImage(INPUT_IMAGE, clobbered_blocks='0')

    # Generate Android data image
    print('- Generating Android data image...')
    b = blockimgdiff.BlockImageDiff(INPUT_IMAGE, version=VERSION)
    b.Compute(OUT_FILE)

    print(f'\nDone! Output directory: {OUT_DIR}')
    return

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='A tool to convert sparse images into Android data images.')

    parser.add_argument('input_image', help='input sparse image')
    parser.add_argument('-o', '--out-dir', default='./', help='output directory (current directory by default)')
    parser.add_argument('-v', '--version', default=4, type=int, help='transfer list format version (version 4 by default)')

    args = parser.parse_args()

    main(args.input_image, args.out_dir, args.version)
