#!/usr/bin/env python3

import brotli, os, sys

sys.path.append('./releasetools')
from releasetools import blockimgdiff, common, images, sparse_img

def main(INPUT_IMAGE, compress, OUT_DIR, VERSION):
    __version__ = '2.0'
    print('img2sdat binary - version: %s' % __version__)

    if not os.path.isdir(OUT_DIR):
        os.makedirs(OUT_DIR)

    OUT_FILE = os.path.join(OUT_DIR, os.path.splitext(os.path.basename(INPUT_IMAGE))[0])

    blockimgdiff.common.OPTIONS.cache_size = 4 * 4096

    # Construct image
    if common.IsSparseImage(INPUT_IMAGE):
        INPUT_IMAGE = sparse_img.SparseImage(INPUT_IMAGE, clobbered_blocks='0')
    else:
        INPUT_IMAGE = images.FileImage(INPUT_IMAGE)

    # Generate Android data image
    print('- Generating Android data image...')
    b = blockimgdiff.BlockImageDiff(INPUT_IMAGE, version=VERSION, disable_imgdiff=True)
    b.Compute(OUT_FILE)

    # Compress image with brotli if specified
    if compress:
        CHUNK_SIZE = 4096 * 4096
        OUT_FILE = f'{OUT_FILE}.new.dat'
        OUT_FILE_BR = f'{OUT_FILE}.br'

        print('- Compressing image with brotli...')
        with open(OUT_FILE, 'rb') as dat_in, open(OUT_FILE_BR, 'wb') as dat_out:
            compressor = brotli.Compressor(quality=6)
            while chunk := dat_in.read(CHUNK_SIZE):
                dat_out.write(compressor.process(chunk))
            dat_out.write(compressor.finish())
        os.remove(OUT_FILE)

    print(f'\nDone! Output directory: {OUT_DIR}')
    return

if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(description='A tool to convert partition images into Android data images.')

    parser.add_argument('input_image', help='input partition image')
    parser.add_argument('-b', '--brotli', action='store_true', help='compress data image with brotli')
    parser.add_argument('-o', '--out-dir', default='./', help='output directory (current directory by default)')
    parser.add_argument('-v', '--version', default=4, type=int, help='transfer list format version (version 4 by default)')

    args = parser.parse_args()

    main(args.input_image, args.brotli, args.out_dir, args.version)
